// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: products.proto

package product_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductGrpcService_GetAllProducts_FullMethodName = "/ProductGrpcService/GetAllProducts"
)

// ProductGrpcServiceClient is the client API for ProductGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductGrpcServiceClient interface {
	GetAllProducts(ctx context.Context, in *GetAllProductsRequest, opts ...grpc.CallOption) (*GetAllProductsResponse, error)
}

type productGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductGrpcServiceClient(cc grpc.ClientConnInterface) ProductGrpcServiceClient {
	return &productGrpcServiceClient{cc}
}

func (c *productGrpcServiceClient) GetAllProducts(ctx context.Context, in *GetAllProductsRequest, opts ...grpc.CallOption) (*GetAllProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllProductsResponse)
	err := c.cc.Invoke(ctx, ProductGrpcService_GetAllProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductGrpcServiceServer is the server API for ProductGrpcService service.
// All implementations should embed UnimplementedProductGrpcServiceServer
// for forward compatibility.
type ProductGrpcServiceServer interface {
	GetAllProducts(context.Context, *GetAllProductsRequest) (*GetAllProductsResponse, error)
}

// UnimplementedProductGrpcServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductGrpcServiceServer struct{}

func (UnimplementedProductGrpcServiceServer) GetAllProducts(context.Context, *GetAllProductsRequest) (*GetAllProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllProducts not implemented")
}
func (UnimplementedProductGrpcServiceServer) testEmbeddedByValue() {}

// UnsafeProductGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductGrpcServiceServer will
// result in compilation errors.
type UnsafeProductGrpcServiceServer interface {
	mustEmbedUnimplementedProductGrpcServiceServer()
}

func RegisterProductGrpcServiceServer(s grpc.ServiceRegistrar, srv ProductGrpcServiceServer) {
	// If the following call pancis, it indicates UnimplementedProductGrpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductGrpcService_ServiceDesc, srv)
}

func _ProductGrpcService_GetAllProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductGrpcServiceServer).GetAllProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductGrpcService_GetAllProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductGrpcServiceServer).GetAllProducts(ctx, req.(*GetAllProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductGrpcService_ServiceDesc is the grpc.ServiceDesc for ProductGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ProductGrpcService",
	HandlerType: (*ProductGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllProducts",
			Handler:    _ProductGrpcService_GetAllProducts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "products.proto",
}
