// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: permissions.proto

package permission_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PermissionGrpcService_GetUserPermissions_FullMethodName = "/PermissionGrpcService/GetUserPermissions"
)

// PermissionGrpcServiceClient is the client API for PermissionGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PermissionGrpcServiceClient interface {
	GetUserPermissions(ctx context.Context, in *GetUserPermissionsRequest, opts ...grpc.CallOption) (*GetUserPermissionsResponse, error)
}

type permissionGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPermissionGrpcServiceClient(cc grpc.ClientConnInterface) PermissionGrpcServiceClient {
	return &permissionGrpcServiceClient{cc}
}

func (c *permissionGrpcServiceClient) GetUserPermissions(ctx context.Context, in *GetUserPermissionsRequest, opts ...grpc.CallOption) (*GetUserPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserPermissionsResponse)
	err := c.cc.Invoke(ctx, PermissionGrpcService_GetUserPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PermissionGrpcServiceServer is the server API for PermissionGrpcService service.
// All implementations should embed UnimplementedPermissionGrpcServiceServer
// for forward compatibility.
type PermissionGrpcServiceServer interface {
	GetUserPermissions(context.Context, *GetUserPermissionsRequest) (*GetUserPermissionsResponse, error)
}

// UnimplementedPermissionGrpcServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPermissionGrpcServiceServer struct{}

func (UnimplementedPermissionGrpcServiceServer) GetUserPermissions(context.Context, *GetUserPermissionsRequest) (*GetUserPermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPermissions not implemented")
}
func (UnimplementedPermissionGrpcServiceServer) testEmbeddedByValue() {}

// UnsafePermissionGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PermissionGrpcServiceServer will
// result in compilation errors.
type UnsafePermissionGrpcServiceServer interface {
	mustEmbedUnimplementedPermissionGrpcServiceServer()
}

func RegisterPermissionGrpcServiceServer(s grpc.ServiceRegistrar, srv PermissionGrpcServiceServer) {
	// If the following call pancis, it indicates UnimplementedPermissionGrpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PermissionGrpcService_ServiceDesc, srv)
}

func _PermissionGrpcService_GetUserPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionGrpcServiceServer).GetUserPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionGrpcService_GetUserPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionGrpcServiceServer).GetUserPermissions(ctx, req.(*GetUserPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PermissionGrpcService_ServiceDesc is the grpc.ServiceDesc for PermissionGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PermissionGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PermissionGrpcService",
	HandlerType: (*PermissionGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserPermissions",
			Handler:    _PermissionGrpcService_GetUserPermissions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "permissions.proto",
}
