definitions:
  GetCategoriesResult:
    properties:
      items:
        items:
          $ref: '#/definitions/github_com_tguankheng016_go-ecommerce-microservice_internal_services_product_service_categories_dtos.CategoryDto'
        type: array
      totalCount:
        type: integer
    type: object
  github_com_tguankheng016_go-ecommerce-microservice_internal_services_product_service_categories_dtos.CategoryDto:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/products/categories:
    get:
      consumes:
      - application/json
      description: Get all categories
      parameters:
      - in: query
        name: filters
        type: string
      - in: query
        name: maxResultCount
        type: integer
      - in: query
        name: skipCount
        type: integer
      - in: query
        name: sorting
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GetCategoriesResult'
      security:
      - ApiKeyAuth: []
      summary: Get all categories
      tags:
      - Categories
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
