// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: identities.proto

package identity_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentityGrpcService_ValidateKey_FullMethodName           = "/IdentityGrpcService/ValidateKey"
	IdentityGrpcService_ValidateSecurityStamp_FullMethodName = "/IdentityGrpcService/ValidateSecurityStamp"
)

// IdentityGrpcServiceClient is the client API for IdentityGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentityGrpcServiceClient interface {
	ValidateKey(ctx context.Context, in *GetValidateTokenKeyRequest, opts ...grpc.CallOption) (*GetValidateTokenKeyResponse, error)
	ValidateSecurityStamp(ctx context.Context, in *GetValidateSecurityStampRequest, opts ...grpc.CallOption) (*GetValidateSecurityStampResponse, error)
}

type identityGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityGrpcServiceClient(cc grpc.ClientConnInterface) IdentityGrpcServiceClient {
	return &identityGrpcServiceClient{cc}
}

func (c *identityGrpcServiceClient) ValidateKey(ctx context.Context, in *GetValidateTokenKeyRequest, opts ...grpc.CallOption) (*GetValidateTokenKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetValidateTokenKeyResponse)
	err := c.cc.Invoke(ctx, IdentityGrpcService_ValidateKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityGrpcServiceClient) ValidateSecurityStamp(ctx context.Context, in *GetValidateSecurityStampRequest, opts ...grpc.CallOption) (*GetValidateSecurityStampResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetValidateSecurityStampResponse)
	err := c.cc.Invoke(ctx, IdentityGrpcService_ValidateSecurityStamp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityGrpcServiceServer is the server API for IdentityGrpcService service.
// All implementations should embed UnimplementedIdentityGrpcServiceServer
// for forward compatibility.
type IdentityGrpcServiceServer interface {
	ValidateKey(context.Context, *GetValidateTokenKeyRequest) (*GetValidateTokenKeyResponse, error)
	ValidateSecurityStamp(context.Context, *GetValidateSecurityStampRequest) (*GetValidateSecurityStampResponse, error)
}

// UnimplementedIdentityGrpcServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityGrpcServiceServer struct{}

func (UnimplementedIdentityGrpcServiceServer) ValidateKey(context.Context, *GetValidateTokenKeyRequest) (*GetValidateTokenKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateKey not implemented")
}
func (UnimplementedIdentityGrpcServiceServer) ValidateSecurityStamp(context.Context, *GetValidateSecurityStampRequest) (*GetValidateSecurityStampResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateSecurityStamp not implemented")
}
func (UnimplementedIdentityGrpcServiceServer) testEmbeddedByValue() {}

// UnsafeIdentityGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityGrpcServiceServer will
// result in compilation errors.
type UnsafeIdentityGrpcServiceServer interface {
	mustEmbedUnimplementedIdentityGrpcServiceServer()
}

func RegisterIdentityGrpcServiceServer(s grpc.ServiceRegistrar, srv IdentityGrpcServiceServer) {
	// If the following call pancis, it indicates UnimplementedIdentityGrpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityGrpcService_ServiceDesc, srv)
}

func _IdentityGrpcService_ValidateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValidateTokenKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityGrpcServiceServer).ValidateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityGrpcService_ValidateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityGrpcServiceServer).ValidateKey(ctx, req.(*GetValidateTokenKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityGrpcService_ValidateSecurityStamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValidateSecurityStampRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityGrpcServiceServer).ValidateSecurityStamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityGrpcService_ValidateSecurityStamp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityGrpcServiceServer).ValidateSecurityStamp(ctx, req.(*GetValidateSecurityStampRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityGrpcService_ServiceDesc is the grpc.ServiceDesc for IdentityGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "IdentityGrpcService",
	HandlerType: (*IdentityGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateKey",
			Handler:    _IdentityGrpcService_ValidateKey_Handler,
		},
		{
			MethodName: "ValidateSecurityStamp",
			Handler:    _IdentityGrpcService_ValidateSecurityStamp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "identities.proto",
}
