// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.12.4
// source: identities.proto

package identity_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetValidateTokenKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CacheKey string `protobuf:"bytes,1,opt,name=cache_key,json=cacheKey,proto3" json:"cache_key,omitempty"`
	UserId   int64  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TokenKey string `protobuf:"bytes,3,opt,name=token_key,json=tokenKey,proto3" json:"token_key,omitempty"`
}

func (x *GetValidateTokenKeyRequest) Reset() {
	*x = GetValidateTokenKeyRequest{}
	mi := &file_identities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValidateTokenKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValidateTokenKeyRequest) ProtoMessage() {}

func (x *GetValidateTokenKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValidateTokenKeyRequest.ProtoReflect.Descriptor instead.
func (*GetValidateTokenKeyRequest) Descriptor() ([]byte, []int) {
	return file_identities_proto_rawDescGZIP(), []int{0}
}

func (x *GetValidateTokenKeyRequest) GetCacheKey() string {
	if x != nil {
		return x.CacheKey
	}
	return ""
}

func (x *GetValidateTokenKeyRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetValidateTokenKeyRequest) GetTokenKey() string {
	if x != nil {
		return x.TokenKey
	}
	return ""
}

type GetValidateTokenKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsValid bool `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
}

func (x *GetValidateTokenKeyResponse) Reset() {
	*x = GetValidateTokenKeyResponse{}
	mi := &file_identities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValidateTokenKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValidateTokenKeyResponse) ProtoMessage() {}

func (x *GetValidateTokenKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValidateTokenKeyResponse.ProtoReflect.Descriptor instead.
func (*GetValidateTokenKeyResponse) Descriptor() ([]byte, []int) {
	return file_identities_proto_rawDescGZIP(), []int{1}
}

func (x *GetValidateTokenKeyResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

type GetValidateSecurityStampRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CacheKey      string `protobuf:"bytes,1,opt,name=cache_key,json=cacheKey,proto3" json:"cache_key,omitempty"`
	UserId        int64  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SecurityStamp string `protobuf:"bytes,3,opt,name=security_stamp,json=securityStamp,proto3" json:"security_stamp,omitempty"`
}

func (x *GetValidateSecurityStampRequest) Reset() {
	*x = GetValidateSecurityStampRequest{}
	mi := &file_identities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValidateSecurityStampRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValidateSecurityStampRequest) ProtoMessage() {}

func (x *GetValidateSecurityStampRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValidateSecurityStampRequest.ProtoReflect.Descriptor instead.
func (*GetValidateSecurityStampRequest) Descriptor() ([]byte, []int) {
	return file_identities_proto_rawDescGZIP(), []int{2}
}

func (x *GetValidateSecurityStampRequest) GetCacheKey() string {
	if x != nil {
		return x.CacheKey
	}
	return ""
}

func (x *GetValidateSecurityStampRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetValidateSecurityStampRequest) GetSecurityStamp() string {
	if x != nil {
		return x.SecurityStamp
	}
	return ""
}

type GetValidateSecurityStampResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsValid bool `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
}

func (x *GetValidateSecurityStampResponse) Reset() {
	*x = GetValidateSecurityStampResponse{}
	mi := &file_identities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValidateSecurityStampResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValidateSecurityStampResponse) ProtoMessage() {}

func (x *GetValidateSecurityStampResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValidateSecurityStampResponse.ProtoReflect.Descriptor instead.
func (*GetValidateSecurityStampResponse) Descriptor() ([]byte, []int) {
	return file_identities_proto_rawDescGZIP(), []int{3}
}

func (x *GetValidateSecurityStampResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

var File_identities_proto protoreflect.FileDescriptor

var file_identities_proto_rawDesc = []byte{
	0x0a, 0x10, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x6f, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x63, 0x68, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x4b, 0x65, 0x79, 0x22, 0x38, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x22, 0x7e, 0x0a,
	0x1f, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x63, 0x75,
	0x72, 0x69, 0x74, 0x79, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x63, 0x68, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69,
	0x74, 0x79, 0x5f, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x3d, 0x0a,
	0x20, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x63, 0x75,
	0x72, 0x69, 0x74, 0x79, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x32, 0xc1, 0x01, 0x0a,
	0x13, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x47, 0x72, 0x70, 0x63, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0b, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x4b, 0x65, 0x79, 0x12, 0x1b, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x5e, 0x0a, 0x15, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x63, 0x75,
	0x72, 0x69, 0x74, 0x79, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x20, 0x2e, 0x47, 0x65, 0x74, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x53,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x47, 0x65,
	0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74,
	0x79, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x15, 0x5a, 0x13, 0x2e, 0x2f, 0x3b, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_identities_proto_rawDescOnce sync.Once
	file_identities_proto_rawDescData = file_identities_proto_rawDesc
)

func file_identities_proto_rawDescGZIP() []byte {
	file_identities_proto_rawDescOnce.Do(func() {
		file_identities_proto_rawDescData = protoimpl.X.CompressGZIP(file_identities_proto_rawDescData)
	})
	return file_identities_proto_rawDescData
}

var file_identities_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_identities_proto_goTypes = []any{
	(*GetValidateTokenKeyRequest)(nil),       // 0: GetValidateTokenKeyRequest
	(*GetValidateTokenKeyResponse)(nil),      // 1: GetValidateTokenKeyResponse
	(*GetValidateSecurityStampRequest)(nil),  // 2: GetValidateSecurityStampRequest
	(*GetValidateSecurityStampResponse)(nil), // 3: GetValidateSecurityStampResponse
}
var file_identities_proto_depIdxs = []int32{
	0, // 0: IdentityGrpcService.ValidateKey:input_type -> GetValidateTokenKeyRequest
	2, // 1: IdentityGrpcService.ValidateSecurityStamp:input_type -> GetValidateSecurityStampRequest
	1, // 2: IdentityGrpcService.ValidateKey:output_type -> GetValidateTokenKeyResponse
	3, // 3: IdentityGrpcService.ValidateSecurityStamp:output_type -> GetValidateSecurityStampResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_identities_proto_init() }
func file_identities_proto_init() {
	if File_identities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_identities_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identities_proto_goTypes,
		DependencyIndexes: file_identities_proto_depIdxs,
		MessageInfos:      file_identities_proto_msgTypes,
	}.Build()
	File_identities_proto = out.File
	file_identities_proto_rawDesc = nil
	file_identities_proto_goTypes = nil
	file_identities_proto_depIdxs = nil
}
